---
title: "Examen_II_G2-C31523-OlmanCamacho"
author: "Olman Camacho"
format: html
editor: visual
---

# Pregunta 1 Cargar el Archivo y librerias
```{r}
library(tidyverse)
library(openxlsx)
moras <- read.xlsx("moras para R.xlsx")
```

# Pregunta 2
```{r}
moras %>%
  summarise(
    MINIMO = min(SALARIO, na.rm = TRUE),
    Q1 = quantile(SALARIO, 0.25, na.rm = TRUE),
    MEDIANA = median(SALARIO, na.rm = TRUE),
    Q3 = quantile(SALARIO, 0.75, na.rm = TRUE),
    MAXIMO = max(SALARIO, na.rm = TRUE),
    PROMEDIO = mean(SALARIO, na.rm = TRUE)
  )

moras %>%
  summarise(
    MINIMO = min(EDAD, na.rm = TRUE),
    Q1 = quantile(EDAD, 0.25, na.rm = TRUE),
    MEDIANA = median(EDAD, na.rm = TRUE),
    Q3 = quantile(EDAD, 0.75, na.rm = TRUE),
    MAXIMO = max(EDAD, na.rm = TRUE),
    PROMEDIO = mean(EDAD, na.rm = TRUE)
  )
```

# Pregunta 3
```{r}
## Z-Score de Salario
zscore_Salario <- abs((moras$SALARIO - mean(moras$SALARIO, na.rm = TRUE)) /
              sd(moras$SALARIO, na.rm = TRUE))

zscore_Edad <- abs((moras$EDAD - mean(moras$EDAD, na.rm = TRUE)) /
              sd(moras$EDAD, na.rm = TRUE))

moras <- moras %>%
  mutate(
    Z_Score_Salario = case_when(
      is.na(zscore_Salario) ~ "FALTANTE",
      zscore_Salario > 1.96 ~ "ATÍPICO",
      TRUE ~ "NO ATÍPICO"
    ),
    Z_Score_Edad = case_when(
      is.na(zscore_Edad) ~ "FALTANTE",
      zscore_Edad > 1.96 ~ "ATÍPICO",
      TRUE ~ "NO ATÍPICO"
  )
)
moras
```

# Pregunta 4
```{r}
colMeans(is.na(moras)) * 100
```

# Pregunta 5
```{r}
## Calcular la moda para imputar los categóricos
calcular_moda <- function(x) {
  frecuencias <- table(x)
  moda <- names(frecuencias)[which.max(frecuencias)]
}
## Imputar SALARIO con la media
moras <- moras %>%
  mutate(
    SALARIO_IMPUTADO = if_else(
      is.na(SALARIO),
      mean(SALARIO, na.rm = TRUE),
      SALARIO
    )
  )

## Imputar EDAD con la media
moras <- moras %>%
  mutate(
    EDAD_IMPUTADO = if_else(
      is.na(EDAD),
      mean(EDAD, na.rm = TRUE),
      EDAD
    )
  )

## Imputar TIPO_ASEGURAMIENTO con la media
moras <- moras %>%
  mutate(
    TIPO_ASEGURAMIENTO_IMPUTADO = if_else(
      is.na(TIPO_ASEGURAMIENTO),
      calcular_moda(TIPO_ASEGURAMIENTO),
      TIPO_ASEGURAMIENTO
    )
  )
moras
```

# Pregunta 6
```{r}
## Gráfico SEXO
moras %>%
  count(SEXO) %>%
  ggplot(aes(x = SEXO, y = n)) +
  geom_col(fill = "#8027F5") +
  geom_text(aes(label = n),
            size = 4) +
  labs(title = "Distribución de SEXO", x = "SEXO", y = "Cantidad de individuos")
### Se observan más individuos de género Masculino que femenino, en la muestra

## Gráfico Sector
moras %>%
  count(SECTOR) %>%
  ggplot(aes(x = SECTOR, y = n)) +
  geom_col(fill = "#8027F5") +
  geom_text(aes(label = n),
            size = 4) +
  labs(title = "Distribución de SECTOR", x = "SECTOR", y = "Cantidad de individuos")
### Según la muestra hay más individuos del sector Privado que del sector Público.					
					
## Gráfico INDICADOR.EXTRANJERO
moras %>%
  count(INDICADOR.EXTRANJERO) %>%
  ggplot(aes(x = INDICADOR.EXTRANJERO, y = n)) +
  geom_col(fill = "#8027F5") +
  geom_text(aes(label = n),
            size = 4) +
  labs(title = "Distribución de INDICADOR.EXTRANJERO", x = "INDICADOR.EXTRANJERO", y = "Cantidad de individuos")
### La muestra refleja más individuos nacionales, en comparación con los individuos extranjeros.					
					
## Gráfico TIPO_ASEGURAMIENTO_IMPUTADO
moras %>%
  count(TIPO_ASEGURAMIENTO_IMPUTADO) %>%
  ggplot(aes(x = TIPO_ASEGURAMIENTO_IMPUTADO, y = n)) +
  geom_col(fill = "#8027F5") +
  geom_text(aes(label = n),
            size = 4) +
  labs(title = "Distribución de TIPO_ASEGURAMIENTO_IMPUTADO", x = "TIPO_ASEGURAMIENTO_IMPUTADO", y = "Cantidad de individuos") +
  coord_flip()
### Observe que la categoría de "Convenios Especiales De Asegurados Voluntarios" es la categoría que menos individuos posee la menor cantidad en comparación con "Asalariado", que acapara más del 50% de los datos.					
					
## Gráfico INDICADOR_ACTIVO
moras %>%
  count(INDICADOR_ACTIVO) %>%
  ggplot(aes(x = INDICADOR_ACTIVO, y = n)) +
  geom_col(fill = "#8027F5") +
  geom_text(aes(label = n),
            size = 4) +
  labs(title = "Distribución de INDICADOR_ACTIVO", x = "INDICADOR_ACTIVO", y = "Cantidad de individuos")
### En la muestra se observan más individuos que poseen el seguro activo, en comparación con los que no lo tienen.					
					
## Gráfico INDICADOR_MOROSO
moras %>%
  count(INDICADOR_MOROSO) %>%
  ggplot(aes(x = INDICADOR_MOROSO, y = n)) +
  geom_col(fill = "#8027F5") +
  geom_text(aes(label = n),
            size = 4) +
  labs(title = "Distribución de INDICADOR_MOROSO", x = "INDICADOR_MOROSO", y = "Cantidad de individuos")
### En la muestra se observan menos individuos en condición de morosidad en contraste con los individuos que no tienen deudas.
```

